### ISSUE TITLE
Plugin interfering with relative paths relative to --config-file

### ISSUE THREAD

**Issue by aw185176** [oprypin/mkdocs-same-dir#7]
It appears that this plugin might be breaking the standard mkdocs behavior of evaluating paths in the config file relative to the file. If I do something like `mkdocs build --config-file=docs/mkdocs.yaml`, I get errors that my various configs don't exist:

```
ERROR   -  Config value 'theme': The path set in custom_dir ('docs/theme') does not exist.
ERROR   -  Config value 'watch': The path 'docs/theme/' isn't an existing file or directory.
```

The config file uses the relative path `theme` in both places, and the printed paths do exist relative to cwd.

**Comment by oprypin** [comment]
Paths in `theme` and `watch` are relative to mkdocs.yml so in fact everything seems to be working correctly.

And come on, you're posting a bug report about mkdocs.yml, how can you not post the content of mkdocs.yml at least 😕

**Comment by oprypin** [comment]
And the file layout too pls

**Comment by aw185176** [comment]
My b, I thought I provided enough context. Let me scrub my config file down to the relevant parts:

```yaml
[...]

docs_dir: .
site_dir: ../dist

not_in_nav: |
  /index.md

# Additional sources to watch during `mkdocs serve`
watch:
- main.py
- teams.yaml
- theme/

theme:
  name: 'material'
  custom_dir: theme
  features:
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#setting-up-navigation
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.tracking
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - toc.integrate
    - toc.follow
  favicon: assets/favicon.svg

[...]
```


Directory structure

```sh
docs
├── assets
├── bin
├── contrib
├── decisions
├── dev
├── mkdocs.yaml
└── theme
```

You can see that the paths for those pieces are in fact relative to `docs/mkdocs.yaml`, which is why I'm confused as to the error message, which does in fact print a valid path. Everything works as expected if I invoke `mkdocs` from the `docs` directory instead.
