### ISSUE TITLE
Regression with mkdocstrings>=23.0.0 dependency

### ISSUE THREAD

**Issue by wesleykendall** [oprypin/mkdocs-same-dir#8]
Hello, thanks for this wonderful plugin!

I noticed my doc builds started failing whenever mkdocstrings was upgraded to 0.24.0. If I upgrade this package in my environment, the `same-dir` plugin fails with the following message:

```
  File ".../mkdocs_same_dir/plugin.py", line 40, in _replace_validation
    config["docs_dir"] = os.path.join(config["docs_dir"], ".")
                                      ~~~~~~^^^^^^^^^^^^
KeyError: 'docs_dir'
```

Thought I'd report this here for now since I'm not sure how another plugin would interfere with this one. For now I simply pin mkdocstrings to 0.23.0

**Comment by oprypin** [comment]
Hmm it works for me, I don't observe the same error. You should share your site that exhibits this

**Comment by oprypin** [comment]
Let me know if you have more to share

**Comment by vstrimaitis** [comment]
Hey! Just encountered the same issue with `mkdocstrings==0.24.0` and `mkdocs-same-dir==0.1.2`. As a workaround, I can set the `mkdocs.yml` config like so:

```yaml
plugins:
- mkdocstrings:
    docs_dir: .  # this does nothing, but fixes the KeyError
    # ...
# ...
```

but that's not nice 😁 

Here's a small `docs/mkdocs.yml` file to reproduce the issue:

```yaml
site_name: Test
docs_dir: .
site_dir: ../site
repo_name: test-repo
plugins:
- same-dir
- mkdocstrings
```

Notice that `same-dir` comes before `mkdocstrings`. If I put it after, the exception is not raised.

Also here's my `pyproject.toml` file that I used to reproduce the issue (run `poetry install --no-root` to set everything up):

```toml
[tool.poetry]
name = "repro"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.9"
mkdocstrings = "0.24.0"
mkdocs-same-dir = "0.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
