### ISSUE TITLE
documentation should mention that `mkdocs` still needs to be run in the same working directory as the `mkdocs.yml` file

### ISSUE THREAD

**Issue by DetachHead** [oprypin/mkdocs-same-dir#9]
i was confused as to how this plugin was supposed to work because my project is structured like so:

```
.
├── docs/
│   ├── index.md
│   └── mkdocs.yml
└── src/
    └── foo.py
```

```yaml
# ./docs/mkdocs.yml

site_name: foo
docs_dir: .
site_dir: ../site

plugins:
  - search
  - same-dir
```

and running `mkdocs serve` results in the following error:

```
Error: Config file 'mkdocs.yml' does not exist.
```

since `mkdocs` doesn't have an option to specify the path to the config file i was wondering if this plugin was supposed to somehow run before the config file gets loaded or something
